webtalk_init -webtalk_dir C:/Users/user/VivadoProjects/2018-3/2026_labs/CheparinAM/Lab4_Project_1/Lab4.sim/sim_2/behav/xsim/xsim.dir/Lab4_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 22 22:52:20 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "981d1dd0-affc-4db1-9168-4771d23a7261" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "322c61fd50924afc90817758edcd7c5f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3418 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "13" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8036_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3932632096 -regid "" -xml C:/Users/user/VivadoProjects/2018-3/2026_labs/CheparinAM/Lab4_Project_1/Lab4.sim/sim_2/behav/xsim/xsim.dir/Lab4_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/user/VivadoProjects/2018-3/2026_labs/CheparinAM/Lab4_Project_1/Lab4.sim/sim_2/behav/xsim/xsim.dir/Lab4_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/user/VivadoProjects/2018-3/2026_labs/CheparinAM/Lab4_Project_1/Lab4.sim/sim_2/behav/xsim/xsim.dir/Lab4_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
